apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spire

resources:
# this one on top since others depend on it
- spire-namespace.yaml
# alphabetically:
- agent-account.yaml
- agent-cluster-role.yaml
- agent-daemonset.yaml
- leader-election-role.yaml
- leader-election-rolebinding.yaml
- manager-role-cluster-role.yaml
- manager-role-cluster-rolebinding.yaml
- server-account.yaml
- server-bundle-endpoint.yaml
- server-cluster-role.yaml
- server-service.yaml
- server-statefulset.yaml
- spiffe-csi-driver.yaml
- spire-bundle-configmap.yaml
- spire-controller-manager-webhook-service.yaml
- spire-controller-manager-webhook.yaml
