apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
  - name: test-container
    image: ubuntu
    command:
      - "bash"
    args:  # apt inside a pod!? Heresy! But I'm lazy.
      - "-c"
      - "apt update; apt install -y curl dnsutils; sleep infinity"
