apiVersion: spire.spiffe.io/v1alpha1
kind: ControllerManagerConfig
metrics:
  bindAddress: 127.0.0.1:8082
health:
  healthProbeBindAddress: 0.0.0.0:8083
leaderElection:
  leaderElect: true
  resourceName: 98c9c988.spiffe.io
  resourceNamespace: spire
clusterName: cluster-0
logLevel: info
trustDomain: cluster-0.k8s.spire.cxcc.nl
ignoreNamespaces:
  - kube-system
  - kube-public
  - spire
  # - local-path-storage