apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
   - port: 8080
     name: http
  selector:
      app: backend
