apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend
spec:
  ports:
   - port: 3000
     name: http
     protocol: TCP
     targetPort: 3000
  selector:
      app: frontend
  type: LoadBalancer
